file_or_repo,status
https://github.com/paul-buerkner/psis-non-factorized-paper,No requirements found
https://github.com/trangvu/ape-npi,No requirements found
https://github.com/bprabhakar/text-to-image,Success
https://github.com/facebookresearch/InferSent,No requirements found
https://github.com/casacore/casarest,No requirements found
https://github.com/yingutk/NL-MAT,No requirements found
https://github.com/xianggebenben/TSSM,No requirements found
https://github.com/enalisnick/stick-breaking_dgms,No requirements found
https://github.com/Maymaher/StackGANv2,No matching distribution found
https://github.com/boyangumn/DCN,No requirements found
https://github.com/quantumprotocolzoo/protocols,No requirements found
https://github.com/Glorf/recipenlg,"Failed:   error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
      rather than 'sklearn' for pip commands.
      
      Here is how to fix this error in the main use cases:
      - use 'pip install scikit-learn' rather than 'pip install sklearn'
      - replace 'sklearn' by 'scikit-learn' in your pip requirements files
        (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
      - if the 'sklearn' package is used by one of your dependencies,
        it would be great if you take some time to track which package uses
        'sklearn' instead of 'scikit-learn' and report it to their issue tracker
      - as a last resort, set the environment variable
        SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error
      
      More information is available at
      https://github.com/scikit-learn/sklearn-pypi-package
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
"
https://github.com/LIBOL/ODL,No requirements found
https://github.com/leondgarse/keras_cv_attention_models/tree/main/keras_cv_attention_models/mobilenetv3_family,No requirements found
https://github.com/geekJZY/arcticnet,No requirements found
https://github.com/Yochengliu/MLIC-KD-WSD,No requirements found
https://github.com/HoganZhang/few-shot-gnn,No requirements found
https://github.com/syahdeini/gan,No requirements found
https://github.com/Neo-The1/ThinkingTicTacToe,No requirements found
https://github.com/trongnghia00/darknet,No requirements found
https://github.com/brandonrobertz/AcademicUrlTitles,"Failed:   error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      Traceback (most recent call last):
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmp7znr4_i7/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py"", line 353, in <module>
          main()
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmp7znr4_i7/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py"", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmp7znr4_i7/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py"", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-build-env-zim9up6y/overlay/lib/python3.12/site-packages/setuptools/build_meta.py"", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-build-env-zim9up6y/overlay/lib/python3.12/site-packages/setuptools/build_meta.py"", line 304, in _get_build_requires
          self.run_setup()
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-build-env-zim9up6y/overlay/lib/python3.12/site-packages/setuptools/build_meta.py"", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-build-env-zim9up6y/overlay/lib/python3.12/site-packages/setuptools/build_meta.py"", line 320, in run_setup
          exec(code, locals())
        File ""<string>"", line 22
          print ""Unit tests have failed!""
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
"
https://github.com/co-design-hybrid/co-design-hybrid,No requirements found
https://github.com/arberzela/EfficientNAS,No requirements found
https://github.com/rickyHong/GANTTS-update-repl,No requirements found
https://github.com/0/itensor-linear-rotors,No requirements found
https://github.com/Nhat-Thanh/ESPCN-Pytorch,No requirements found
https://github.com/YGUO29/FANTASIA-CaImAn,No requirements found
https://github.com/ridakadri14/AspectBasedSentimentAnalysis,No requirements found
https://github.com/One-sixth/CVAE-GAN_tensorlayer,No requirements found
https://github.com/takyamamoto/FirstExplicitMethod-HDM,No requirements found
https://github.com/maxime1310/fuzzy_labeling_scRNA,"Failed:   error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [30 lines of output]
      Running from numpy source directory.
      <string>:369: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
      /private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-install-0_olu9ai/numpy_4a7b2791734f42008cd1e61410b0f3bb/numpy/distutils/misc_util.py:464: SyntaxWarning: ""is"" with 'str' literal. Did you mean ""==""?
        return is_string(s) and ('*' in s or '?' is s)
      Traceback (most recent call last):
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmppnwtg7bn/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py"", line 353, in <module>
          main()
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmppnwtg7bn/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py"", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmppnwtg7bn/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py"", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-build-env-luxg19b4/overlay/lib/python3.12/site-packages/setuptools/build_meta.py"", line 377, in prepare_metadata_for_build_wheel
          self.run_setup()
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-build-env-luxg19b4/overlay/lib/python3.12/site-packages/setuptools/build_meta.py"", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-build-env-luxg19b4/overlay/lib/python3.12/site-packages/setuptools/build_meta.py"", line 320, in run_setup
          exec(code, locals())
        File ""<string>"", line 394, in <module>
        File ""<string>"", line 373, in setup_package
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-install-0_olu9ai/numpy_4a7b2791734f42008cd1e61410b0f3bb/numpy/distutils/__init__.py"", line 8, in <module>
          from . import ccompiler
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-install-0_olu9ai/numpy_4a7b2791734f42008cd1e61410b0f3bb/numpy/distutils/ccompiler.py"", line 17, in <module>
          from numpy.distutils import log
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-install-0_olu9ai/numpy_4a7b2791734f42008cd1e61410b0f3bb/numpy/distutils/log.py"", line 13, in <module>
          from numpy.distutils.misc_util import (red_text, default_text, cyan_text,
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-install-0_olu9ai/numpy_4a7b2791734f42008cd1e61410b0f3bb/numpy/distutils/misc_util.py"", line 15, in <module>
          from distutils.msvccompiler import get_build_architecture
      ModuleNotFoundError: No module named 'distutils.msvccompiler'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
"
https://github.com/danielholanda/LeFlow,No requirements found
https://github.com/earlbellinger/thesis,No requirements found
https://github.com/chongkewu/PESC-HPC,No requirements found
https://github.com/Tencent/tencent-ml-images,No requirements found
https://github.com/Jungjaewon/Visual-Relationship-Detection,No requirements found
https://github.com/dare0021/MemN2N_Bench,No requirements found
https://github.com/RobotLocomotion/pytorch-dense-correspondence,No requirements found
https://github.com/lorenzobrusco/ECGNeuralNetwork,Success
https://github.com/tbuikr/3D_DenseSeg,No requirements found
https://github.com/keelm/SeCo-MLC,No requirements found
https://github.com/andgoldschmidt/biDMD-for-quantum,No requirements found
https://github.com/thesps/conifer,No requirements found
https://github.com/Breakend/TemporalYolo,No requirements found
https://github.com/Soumyabrata/color-channels,No requirements found
https://github.com/tomgoter/nlp_finalproject,No requirements found
https://github.com/kmtam/covid19_data,No requirements found
https://github.com/wswu/trabina,No requirements found
https://github.com/paramitamirza/CATENA,No requirements found
https://github.com/xmu-xiaoma666/External-Attention-pytorch/blob/master/attention/PolarizedSelfAttention.py,No requirements found
https://github.com/burcu-can/TreeStructuredDP,No requirements found
https://github.com/aqeel13932/APES,No requirements found
https://github.com/MindSpore-paper-code-3/code7/tree/main/Focus-DETR,No requirements found
https://github.com/gmarceaucaron/natural-langevin-dynamics-for-neural-networks,No requirements found
https://github.com/racerandom/temporalorder,No requirements found
https://github.com/shenjianbing/videoseg15,No requirements found
https://github.com/liamcli/darts,No requirements found
https://github.com/antonFJohansson/Bayesian-Learning-of-Neural-Network-Architectures,No requirements found
https://github.com/manavkulshrestha/imgprov,No requirements found
https://github.com/tianyishan/Blind_Deconvolution,No requirements found
https://github.com/keisuke6616/Distance-based-classifier-by-data-transformation-for-high-dimension-strongly-spiked-eigenvalue-mode,No requirements found
https://github.com/hitvoice/DrQA,Success
https://github.com/leehomyc/Faster-High-Res-Neural-Inpainting,No requirements found
https://github.com/XiaohangZhan/cdp,No requirements found
https://github.com/tlynn747/IrishTwitterPOS,No requirements found
https://github.com/marcellacornia/mlnet,No requirements found
https://github.com/quantummind/qaml-z,No requirements found
https://github.com/Dalkio/RL_rubiks,No requirements found
https://github.com/chihyaoma/Activity-Recognition-with-CNN-and-RNN,No requirements found
https://github.com/Vicky-Wil/topic-NMT,"Failed:   error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
      rather than 'sklearn' for pip commands.
      
      Here is how to fix this error in the main use cases:
      - use 'pip install scikit-learn' rather than 'pip install sklearn'
      - replace 'sklearn' by 'scikit-learn' in your pip requirements files
        (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
      - if the 'sklearn' package is used by one of your dependencies,
        it would be great if you take some time to track which package uses
        'sklearn' instead of 'scikit-learn' and report it to their issue tracker
      - as a last resort, set the environment variable
        SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error
      
      More information is available at
      https://github.com/scikit-learn/sklearn-pypi-package
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
"
https://github.com/user525/mfgpc,No requirements found
https://github.com/YuvalBahat/Confidence_From_Invariance,No requirements found
https://github.com/camponsah/Penalty-Method-Obliquely-Reflected-Diffusions,No requirements found
https://github.com/TatsuyaShirakawa/poincare-embedding,"Failed:   error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [28 lines of output]
      Running from numpy source directory.
      <string>:390: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
      /private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-install-tu2t15kb/numpy_2c29f0d2289d47ffb5de6f88ca3e74e3/numpy/distutils/misc_util.py:476: SyntaxWarning: ""is"" with 'str' literal. Did you mean ""==""?
        return is_string(s) and ('*' in s or '?' is s)
      Traceback (most recent call last):
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmp0hytlsba/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py"", line 353, in <module>
          main()
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmp0hytlsba/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py"", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmp0hytlsba/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py"", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-build-env-w1a645vl/overlay/lib/python3.12/site-packages/setuptools/build_meta.py"", line 377, in prepare_metadata_for_build_wheel
          self.run_setup()
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-build-env-w1a645vl/overlay/lib/python3.12/site-packages/setuptools/build_meta.py"", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-build-env-w1a645vl/overlay/lib/python3.12/site-packages/setuptools/build_meta.py"", line 320, in run_setup
          exec(code, locals())
        File ""<string>"", line 415, in <module>
        File ""<string>"", line 394, in setup_package
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-install-tu2t15kb/numpy_2c29f0d2289d47ffb5de6f88ca3e74e3/numpy/distutils/core.py"", line 26, in <module>
          from numpy.distutils.command import config, config_compiler, \
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-install-tu2t15kb/numpy_2c29f0d2289d47ffb5de6f88ca3e74e3/numpy/distutils/command/config.py"", line 19, in <module>
          from numpy.distutils.mingw32ccompiler import generate_manifest
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-install-tu2t15kb/numpy_2c29f0d2289d47ffb5de6f88ca3e74e3/numpy/distutils/mingw32ccompiler.py"", line 34, in <module>
          from distutils.msvccompiler import get_build_version as get_build_msvc_version
      ModuleNotFoundError: No module named 'distutils.msvccompiler'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
"
https://github.com/bobbyhaliwela/AutoRcCar-Behavioral-Clonning,No requirements found
https://github.com/unsky/focal-loss,No requirements found
https://github.com/benevolentAI/guacamol_baselines,"Failed: ERROR: Invalid requirement: 'dockers/requirements.txt': Expected end or semicolon (after name and no valid version specifier)
    dockers/requirements.txt
           ^ (from line 1 of /var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmp0497oogh)
Hint: It looks like a path. File 'dockers/requirements.txt' does not exist.
"
https://github.com/Babylonpartners/fuzzymax,"Failed:   error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [30 lines of output]
      Running from numpy source directory.
      <string>:378: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
      /private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-install-uz2oqriu/numpy_55fa3454191e475188472daccbf60a2d/numpy/distutils/misc_util.py:477: SyntaxWarning: ""is"" with 'str' literal. Did you mean ""==""?
        return is_string(s) and ('*' in s or '?' is s)
      Traceback (most recent call last):
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmp2_r73rh2/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py"", line 353, in <module>
          main()
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmp2_r73rh2/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py"", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmp2_r73rh2/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py"", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-build-env-l1ea4wor/overlay/lib/python3.12/site-packages/setuptools/build_meta.py"", line 377, in prepare_metadata_for_build_wheel
          self.run_setup()
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-build-env-l1ea4wor/overlay/lib/python3.12/site-packages/setuptools/build_meta.py"", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-build-env-l1ea4wor/overlay/lib/python3.12/site-packages/setuptools/build_meta.py"", line 320, in run_setup
          exec(code, locals())
        File ""<string>"", line 403, in <module>
        File ""<string>"", line 382, in setup_package
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-install-uz2oqriu/numpy_55fa3454191e475188472daccbf60a2d/numpy/distutils/__init__.py"", line 8, in <module>
          from . import ccompiler
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-install-uz2oqriu/numpy_55fa3454191e475188472daccbf60a2d/numpy/distutils/ccompiler.py"", line 17, in <module>
          from numpy.distutils import log
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-install-uz2oqriu/numpy_55fa3454191e475188472daccbf60a2d/numpy/distutils/log.py"", line 13, in <module>
          from numpy.distutils.misc_util import (red_text, default_text, cyan_text,
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-install-uz2oqriu/numpy_55fa3454191e475188472daccbf60a2d/numpy/distutils/misc_util.py"", line 16, in <module>
          from distutils.msvccompiler import get_build_architecture
      ModuleNotFoundError: No module named 'distutils.msvccompiler'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
"
https://github.com/wrld/visual_navigation_pose_estimation,"Failed: ERROR: Invalid requirement: '_libgcc_mutex=0.1=main': Expected package name at the start of dependency specifier
    _libgcc_mutex=0.1=main
    ^ (from line 1 of /var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpigob1e6i)
Hint: = is not a valid operator. Did you mean == ?
"
https://github.com/facebookresearch/higher,"Failed: ERROR: torch-1.2.0+cpu-cp37-cp37m-manylinux1_x86_64.whl is not a supported wheel on this platform.
"
https://github.com/rakshithShetty/captionGAN,No requirements found
https://github.com/simonjisu/NMT,No requirements found
https://github.com/ZiningZhu/feng-hirst-rst-parser,No requirements found
https://github.com/qiuwenhui/StanfordDoggoProject,No requirements found
https://github.com/TEAMLAB-Lecture/deep_nlp_101,No requirements found
https://github.com/txhaug/nisq-sdp,No requirements found
https://github.com/mdabbah/COOD_benchmarking,Success
https://github.com/sshaar/clef2020-factchecking-task2,"Failed:   error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [40 lines of output]
      <string>:31: SetuptoolsDeprecationWarning: The test command is disabled and references to it are deprecated.
      !!
      
              ********************************************************************************
              Please remove any references to `setuptools.command.test` in all supported versions of the affected package.
      
              This deprecation is overdue, please update your project and remove deprecated
              calls to avoid build errors in the future.
              ********************************************************************************
      
      !!
      Traceback (most recent call last):
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpjatooul7/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py"", line 353, in <module>
          main()
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpjatooul7/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py"", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpjatooul7/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py"", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-build-env-x8q0ld0i/overlay/lib/python3.12/site-packages/setuptools/build_meta.py"", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-build-env-x8q0ld0i/overlay/lib/python3.12/site-packages/setuptools/build_meta.py"", line 304, in _get_build_requires
          self.run_setup()
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-build-env-x8q0ld0i/overlay/lib/python3.12/site-packages/setuptools/build_meta.py"", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-build-env-x8q0ld0i/overlay/lib/python3.12/site-packages/setuptools/build_meta.py"", line 320, in run_setup
          exec(code, locals())
        File ""<string>"", line 50, in <module>
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-install-kp6ep925/matplotlib_31512364bbcb40f3a4304f115c1574c5/versioneer.py"", line 1410, in get_version
          return get_versions()[""version""]
                 ^^^^^^^^^^^^^^
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-install-kp6ep925/matplotlib_31512364bbcb40f3a4304f115c1574c5/versioneer.py"", line 1344, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-install-kp6ep925/matplotlib_31512364bbcb40f3a4304f115c1574c5/versioneer.py"", line 401, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
"
https://github.com/Heumi/BEGAN-tensorflow,No requirements found
https://github.com/mrkieumy/task-conditioned,No requirements found
https://github.com/bochencaltech/scotopic,No requirements found
https://github.com/cedricdeboom/CharRNN,No requirements found
https://github.com/learn-co-curriculum/dsc-graph-connectivity-community-detection,No requirements found
https://github.com/kadarakos/chaoticgls,No requirements found
https://github.com/CP-Unibo/sunny-cp,No requirements found
https://github.com/ShinKyuY/Understanding-Black-box-Predictions-via-Influence-Functions-tutorial-MNIST-7-vs-1-Classification,No requirements found
https://github.com/DFKI-NLP/TRE,No matching distribution found
https://github.com/bazenkov/MultiCPG,No requirements found
https://github.com/douglase/poppy_benchmarking,No requirements found
https://github.com/VCL3D/SphericalViewSynthesis,No requirements found
https://github.com/hirokatsukataoka16/FractalDB-Pretrained-ResNet-PyTorch,No requirements found
https://github.com/anonmaths/tumour_sde_model,No requirements found
https://github.com/dennybritz/cnn-text-classification-tf,No requirements found
https://github.com/qilei123/fpn_crop,No matching distribution found
https://github.com/prajjwal1/adaptive_transformer,No matching distribution found
https://github.com/jingxixu/pddlstream,No requirements found
https://github.com/awstlaur/negsnel,No requirements found
https://github.com/invenia/OPFSampler.jl,No requirements found
https://github.com/coin-dataset/annotations,No requirements found
https://github.com/ken90242/js-segment-annotator,No requirements found
https://github.com/HaijunMa/GAN-Getting-started-learning,No requirements found
https://github.com/ronggong/jingjuSingingPhraseMatching,"Failed:   error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [28 lines of output]
      Running from numpy source directory.
      <string>:366: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
      /private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-install-x3flobic/numpy_dc27bf7acd064498a87e4d7d79280edf/numpy/distutils/misc_util.py:453: SyntaxWarning: ""is"" with 'str' literal. Did you mean ""==""?
        return is_string(s) and ('*' in s or '?' is s)
      Traceback (most recent call last):
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpukscehj0/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py"", line 353, in <module>
          main()
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpukscehj0/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py"", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpukscehj0/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py"", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-build-env-pwat3eke/overlay/lib/python3.12/site-packages/setuptools/build_meta.py"", line 377, in prepare_metadata_for_build_wheel
          self.run_setup()
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-build-env-pwat3eke/overlay/lib/python3.12/site-packages/setuptools/build_meta.py"", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-build-env-pwat3eke/overlay/lib/python3.12/site-packages/setuptools/build_meta.py"", line 320, in run_setup
          exec(code, locals())
        File ""<string>"", line 391, in <module>
        File ""<string>"", line 370, in setup_package
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-install-x3flobic/numpy_dc27bf7acd064498a87e4d7d79280edf/numpy/distutils/core.py"", line 26, in <module>
          from numpy.distutils.command import config, config_compiler, \
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-install-x3flobic/numpy_dc27bf7acd064498a87e4d7d79280edf/numpy/distutils/command/config.py"", line 18, in <module>
          from numpy.distutils.mingw32ccompiler import generate_manifest
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-install-x3flobic/numpy_dc27bf7acd064498a87e4d7d79280edf/numpy/distutils/mingw32ccompiler.py"", line 34, in <module>
          from distutils.msvccompiler import get_build_version as get_build_msvc_version
      ModuleNotFoundError: No module named 'distutils.msvccompiler'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
"
https://github.com/TTMRonald/MobileNet_Zoo,No requirements found
https://github.com/koshian2/affinity-loss,No requirements found
https://github.com/impredicative/irc-url-title-bot,"Failed:   error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [38 lines of output]
      /private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-build-env-452t7ghf/overlay/lib/python3.12/site-packages/setuptools_scm/git.py:312: UserWarning: git archive did not support describe output
        warnings.warn(""git archive did not support describe output"")
      WARNING setuptools_scm.pyproject_reading toml section missing 'pyproject.toml does not contain a tool.setuptools_scm section'
      Traceback (most recent call last):
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-build-env-452t7ghf/overlay/lib/python3.12/site-packages/setuptools_scm/_integration/pyproject_reading.py"", line 36, in read_pyproject
          section = defn.get(""tool"", {})[tool_name]
                    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
      KeyError: 'setuptools_scm'
      Traceback (most recent call last):
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpiv95atho/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py"", line 353, in <module>
          main()
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpiv95atho/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py"", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpiv95atho/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py"", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-build-env-452t7ghf/overlay/lib/python3.12/site-packages/setuptools/build_meta.py"", line 377, in prepare_metadata_for_build_wheel
          self.run_setup()
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-build-env-452t7ghf/overlay/lib/python3.12/site-packages/setuptools/build_meta.py"", line 320, in run_setup
          exec(code, locals())
        File ""<string>"", line 66, in <module>
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-build-env-452t7ghf/overlay/lib/python3.12/site-packages/setuptools/__init__.py"", line 117, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-build-env-452t7ghf/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py"", line 157, in setup
          dist.parse_config_files()
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-build-env-452t7ghf/overlay/lib/python3.12/site-packages/setuptools/dist.py"", line 648, in parse_config_files
          pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-build-env-452t7ghf/overlay/lib/python3.12/site-packages/setuptools/config/pyprojecttoml.py"", line 72, in apply_configuration
          config = read_configuration(filepath, True, ignore_option_errors, dist)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-build-env-452t7ghf/overlay/lib/python3.12/site-packages/setuptools/config/pyprojecttoml.py"", line 140, in read_configuration
          validate(subset, filepath)
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-build-env-452t7ghf/overlay/lib/python3.12/site-packages/setuptools/config/pyprojecttoml.py"", line 61, in validate
          raise ValueError(f""{error}\n{summary}"") from None
      ValueError: invalid pyproject.toml config: `project`.
      configuration error: `project` must contain ['name'] properties
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
"
https://github.com/kevinroccapriore/Predictability,No requirements found
https://github.com/kornia/kornia,No requirements found
https://github.com/xuehangzheng/PWLS-ULTRA-for-Low-Dose-3D-CT-Image-Reconstruction,No requirements found
https://github.com/kstawiski/OmicApp,No requirements found
https://github.com/takase/control-length,No requirements found
https://github.com/sfu-gruvi-3dv/Self-Supervised-Human-Depth,"Failed:   error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [26 lines of output]
      Traceback (most recent call last):
        File ""<string>"", line 9, in <module>
      ModuleNotFoundError: No module named 'pip'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmp97y5c1fi/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py"", line 353, in <module>
          main()
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmp97y5c1fi/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py"", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmp97y5c1fi/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py"", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-build-env-ql1dgzm1/overlay/lib/python3.12/site-packages/setuptools/build_meta.py"", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-build-env-ql1dgzm1/overlay/lib/python3.12/site-packages/setuptools/build_meta.py"", line 304, in _get_build_requires
          self.run_setup()
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-build-env-ql1dgzm1/overlay/lib/python3.12/site-packages/setuptools/build_meta.py"", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-build-env-ql1dgzm1/overlay/lib/python3.12/site-packages/setuptools/build_meta.py"", line 320, in run_setup
          exec(code, locals())
        File ""<string>"", line 11, in <module>
      ModuleNotFoundError: No module named 'pip'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
"
https://github.com/alishdipani/Neural-Style-Transfer-Audio,No requirements found
https://github.com/BroCoLySTyLe/SQLovaReview,No requirements found
https://github.com/mari-linhares/tensorflow-maml,No requirements found
https://github.com/seungjaeryanlee/rldb,No requirements found
https://github.com/ziatdinovmax/ChemDisc,No requirements found
https://github.com/tonghelen/JED-Method,No requirements found
https://github.com/tianhai123/yolov3,No requirements found
https://github.com/gitstevendeng/two-halves-statistically-different,No requirements found
https://github.com/GeeLaw/bio-site,No requirements found
https://github.com/adematti/pycute,"Failed: ERROR: Invalid requirement: 'scipy]': Expected end or semicolon (after name and no valid version specifier)
    scipy]
         ^ (from line 2 of /var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmphbv1cn0x)
"
https://github.com/kcmeehan/SmartDetect,No requirements found
https://github.com/ethanhezhao/WEDTM,No requirements found
https://github.com/5m0k3/gwd-yolov5-pytorch,No requirements found
https://github.com/mp2893/mime,No requirements found
https://github.com/chengyangfu/pytorch-groupnormalization,No requirements found
https://github.com/textlab/cglossa,No requirements found
https://github.com/wangsen99/MMoFusion,"Failed: ERROR: Exception:
Traceback (most recent call last):
  File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpsef4iti5/lib/python3.12/site-packages/pip/_internal/cli/base_command.py"", line 105, in _run_wrapper
    status = _inner_run()
             ^^^^^^^^^^^^
  File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpsef4iti5/lib/python3.12/site-packages/pip/_internal/cli/base_command.py"", line 96, in _inner_run
    return self.run(options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpsef4iti5/lib/python3.12/site-packages/pip/_internal/cli/req_command.py"", line 67, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpsef4iti5/lib/python3.12/site-packages/pip/_internal/commands/install.py"", line 379, in run
    requirement_set = resolver.resolve(
                      ^^^^^^^^^^^^^^^^^
  File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpsef4iti5/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/resolver.py"", line 95, in resolve
    result = self._result = resolver.resolve(
                            ^^^^^^^^^^^^^^^^^
  File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpsef4iti5/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py"", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpsef4iti5/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py"", line 397, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpsef4iti5/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py"", line 173, in _add_to_criteria
    if not criterion.candidates:
           ^^^^^^^^^^^^^^^^^^^^
  File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpsef4iti5/lib/python3.12/site-packages/pip/_vendor/resolvelib/structs.py"", line 156, in __bool__
    return bool(self._sequence)
           ^^^^^^^^^^^^^^^^^^^^
  File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpsef4iti5/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py"", line 174, in __bool__
    return any(self)
           ^^^^^^^^^
  File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpsef4iti5/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py"", line 162, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
                       ^^^^^^^^
  File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpsef4iti5/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py"", line 53, in _iter_built
    candidate = func()
                ^^^^^^
  File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpsef4iti5/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/factory.py"", line 187, in _make_candidate_from_link
    base: Optional[BaseCandidate] = self._make_base_candidate_from_link(
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpsef4iti5/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/factory.py"", line 233, in _make_base_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
                                       ^^^^^^^^^^^^^^
  File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpsef4iti5/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py"", line 304, in __init__
    super().__init__(
  File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpsef4iti5/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py"", line 159, in __init__
    self.dist = self._prepare()
                ^^^^^^^^^^^^^^^
  File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpsef4iti5/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py"", line 236, in _prepare
    dist = self._prepare_distribution()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpsef4iti5/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py"", line 315, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpsef4iti5/lib/python3.12/site-packages/pip/_internal/operations/prepare.py"", line 527, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpsef4iti5/lib/python3.12/site-packages/pip/_internal/operations/prepare.py"", line 642, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpsef4iti5/lib/python3.12/site-packages/pip/_internal/operations/prepare.py"", line 72, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpsef4iti5/lib/python3.12/site-packages/pip/_internal/distributions/sdist.py"", line 56, in prepare_distribution_metadata
    self._install_build_reqs(finder)
  File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpsef4iti5/lib/python3.12/site-packages/pip/_internal/distributions/sdist.py"", line 126, in _install_build_reqs
    build_reqs = self._get_build_requires_wheel()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpsef4iti5/lib/python3.12/site-packages/pip/_internal/distributions/sdist.py"", line 103, in _get_build_requires_wheel
    return backend.get_requires_for_build_wheel()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpsef4iti5/lib/python3.12/site-packages/pip/_internal/utils/misc.py"", line 701, in get_requires_for_build_wheel
    return super().get_requires_for_build_wheel(config_settings=cs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpsef4iti5/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_impl.py"", line 166, in get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpsef4iti5/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_impl.py"", line 321, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
  File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpsef4iti5/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py"", line 77, in _build_backend
    obj = import_module(mod_path)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File ""/opt/homebrew/Cellar/python@3.12/3.12.8/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py"", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ""<frozen importlib._bootstrap>"", line 1387, in _gcd_import
  File ""<frozen importlib._bootstrap>"", line 1360, in _find_and_load
  File ""<frozen importlib._bootstrap>"", line 1310, in _find_and_load_unlocked
  File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
  File ""<frozen importlib._bootstrap>"", line 1387, in _gcd_import
  File ""<frozen importlib._bootstrap>"", line 1360, in _find_and_load
  File ""<frozen importlib._bootstrap>"", line 1331, in _find_and_load_unlocked
  File ""<frozen importlib._bootstrap>"", line 935, in _load_unlocked
  File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
  File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
  File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-build-env-y5rq2k8b/overlay/lib/python3.12/site-packages/setuptools/__init__.py"", line 9, in <module>
    import distutils.core
ModuleNotFoundError: No module named 'distutils'

"
https://github.com/kornai/4lang,No requirements found
https://github.com/alexdominguez09/pedestrian_direction,No requirements found
https://github.com/beamandrew/BNN,No requirements found
https://github.com/merrygoat/creep-sheared-gels,No requirements found
https://github.com/rlworkgroup/garage,No matching distribution found
https://github.com/ugent-korea/pytorch-unet-segmentation,No requirements found
https://github.com/JoeMcEwen/FAST-PT,"Failed: ERROR: Invalid requirement: 'matplotlib]': Expected end or semicolon (after name and no valid version specifier)
    matplotlib]
              ^ (from line 3 of /var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmp7wmluymp)
"
https://github.com/nitarshan/robust-generalization-measures,Success
https://github.com/freesunshine0316/semantic-nmt,No requirements found
https://github.com/MrRen-sdhm/Embedded_Multi_Object_Detection_CNN,No requirements found
https://github.com/zswang666/Stereo-LiDAR-CCVNorm,No requirements found
https://github.com/derEitel/explainableMS,No requirements found
https://github.com/acecreamu/color-constancy-googlenet,No requirements found
https://github.com/freedombenLiu/RNN-Time-series-Anomaly-Detection,"Failed:   error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
      rather than 'sklearn' for pip commands.
      
      Here is how to fix this error in the main use cases:
      - use 'pip install scikit-learn' rather than 'pip install sklearn'
      - replace 'sklearn' by 'scikit-learn' in your pip requirements files
        (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
      - if the 'sklearn' package is used by one of your dependencies,
        it would be great if you take some time to track which package uses
        'sklearn' instead of 'scikit-learn' and report it to their issue tracker
      - as a last resort, set the environment variable
        SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error
      
      More information is available at
      https://github.com/scikit-learn/sklearn-pypi-package
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
"
https://github.com/cgcl-codes/attack_ptmc,"Failed:   error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [60 lines of output]
      Ignoring numpy: markers 'python_version == ""3.6"" and platform_system != ""AIX""' don't match your environment
      Ignoring numpy: markers 'python_version == ""3.7"" and platform_system != ""AIX""' don't match your environment
      Ignoring numpy: markers 'python_version == ""3.6"" and platform_system == ""AIX""' don't match your environment
      Ignoring numpy: markers 'python_version == ""3.7"" and platform_system == ""AIX""' don't match your environment
      Ignoring numpy: markers 'python_version >= ""3.8"" and platform_system == ""AIX""' don't match your environment
      Collecting setuptools
        Using cached setuptools-75.6.0-py3-none-any.whl.metadata (6.7 kB)
      Collecting wheel
        Using cached wheel-0.45.1-py3-none-any.whl.metadata (2.3 kB)
      Collecting Cython<3,>=0.29.21
        Using cached Cython-0.29.37-py2.py3-none-any.whl.metadata (3.1 kB)
      Collecting numpy==1.17.3
        Using cached numpy-1.17.3.zip (6.4 MB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error
      
        × Preparing metadata (pyproject.toml) did not run successfully.
        │ exit code: 1
        ╰─> [26 lines of output]
            Running from numpy source directory.
            <string>:418: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
            Traceback (most recent call last):
              File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpubpsv5ym/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py"", line 353, in <module>
                main()
              File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpubpsv5ym/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py"", line 335, in main
                json_out['return_val'] = hook(**hook_input['kwargs'])
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpubpsv5ym/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py"", line 149, in prepare_metadata_for_build_wheel
                return hook(metadata_directory, config_settings)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-build-env-npo7taxh/overlay/lib/python3.12/site-packages/setuptools/build_meta.py"", line 377, in prepare_metadata_for_build_wheel
                self.run_setup()
              File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-build-env-npo7taxh/overlay/lib/python3.12/site-packages/setuptools/build_meta.py"", line 522, in run_setup
                super().run_setup(setup_script=setup_script)
              File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-build-env-npo7taxh/overlay/lib/python3.12/site-packages/setuptools/build_meta.py"", line 320, in run_setup
                exec(code, locals())
              File ""<string>"", line 443, in <module>
              File ""<string>"", line 422, in setup_package
              File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-install-mppo3936/numpy_16acbe0ce7304b6fa7cde27b833e72d0/numpy/distutils/core.py"", line 26, in <module>
                from numpy.distutils.command import config, config_compiler, \
              File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-install-mppo3936/numpy_16acbe0ce7304b6fa7cde27b833e72d0/numpy/distutils/command/config.py"", line 20, in <module>
                from numpy.distutils.mingw32ccompiler import generate_manifest
              File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-install-mppo3936/numpy_16acbe0ce7304b6fa7cde27b833e72d0/numpy/distutils/mingw32ccompiler.py"", line 34, in <module>
                from distutils.msvccompiler import get_build_version as get_build_msvc_version
            ModuleNotFoundError: No module named 'distutils.msvccompiler'
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: metadata-generation-failed
      
      × Encountered error while generating package metadata.
      ╰─> See above for output.
      
      note: This is an issue with the package mentioned above, not pip.
      hint: See above for details.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
"
https://github.com/openai/generating-reviews-discovering-sentiment,No requirements found
https://github.com/michael-goebel/ei_red,No matching distribution found
https://github.com/lazharkhelifi/deeplearning_changedetection_remotesensing_review,No requirements found
https://github.com/houssamzenati/Adversarially-Learned-Anomaly-Detection,No matching distribution found
https://github.com/UnofficialJuliaMirror/HomotopyContinuation.jl-f213a82b-91d6-5c5d-acf7-10f1c761b327,No requirements found
https://github.com/LittleYUYU/StackOverflow-Question-Code-Dataset,No requirements found
https://github.com/yule-li/MassFace,No requirements found
https://github.com/dineshzende/awesome-deep-learning-resources,No requirements found
https://github.com/alfredvc/paac,No requirements found
https://github.com/MLOPTPSU/FedTorch,"Failed:   error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [40 lines of output]
      <string>:32: SetuptoolsDeprecationWarning: The test command is disabled and references to it are deprecated.
      !!
      
              ********************************************************************************
              Please remove any references to `setuptools.command.test` in all supported versions of the affected package.
      
              This deprecation is overdue, please update your project and remove deprecated
              calls to avoid build errors in the future.
              ********************************************************************************
      
      !!
      Traceback (most recent call last):
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpvizm5p36/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py"", line 353, in <module>
          main()
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpvizm5p36/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py"", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpvizm5p36/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py"", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-build-env-_p0xtz8k/overlay/lib/python3.12/site-packages/setuptools/build_meta.py"", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-build-env-_p0xtz8k/overlay/lib/python3.12/site-packages/setuptools/build_meta.py"", line 304, in _get_build_requires
          self.run_setup()
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-build-env-_p0xtz8k/overlay/lib/python3.12/site-packages/setuptools/build_meta.py"", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-build-env-_p0xtz8k/overlay/lib/python3.12/site-packages/setuptools/build_meta.py"", line 320, in run_setup
          exec(code, locals())
        File ""<string>"", line 52, in <module>
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-install-68xdv0z0/matplotlib_98d196fed46446848018efee22e71d32/versioneer.py"", line 1410, in get_version
          return get_versions()[""version""]
                 ^^^^^^^^^^^^^^
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-install-68xdv0z0/matplotlib_98d196fed46446848018efee22e71d32/versioneer.py"", line 1344, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-install-68xdv0z0/matplotlib_98d196fed46446848018efee22e71d32/versioneer.py"", line 401, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
"
https://github.com/shangtse/robust-physical-attack,No requirements found
https://github.com/jsztompka/MultiAgent-PPO,No requirements found
https://github.com/harvitronix/reinforcement-learning-car,No requirements found
https://github.com/ratschlab/boosting-bbvi,"Failed:   error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpedicpjul/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py"", line 353, in <module>
          main()
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpedicpjul/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py"", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpedicpjul/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py"", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-build-env-548a8ah8/overlay/lib/python3.12/site-packages/setuptools/build_meta.py"", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-build-env-548a8ah8/overlay/lib/python3.12/site-packages/setuptools/build_meta.py"", line 304, in _get_build_requires
          self.run_setup()
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-build-env-548a8ah8/overlay/lib/python3.12/site-packages/setuptools/build_meta.py"", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-build-env-548a8ah8/overlay/lib/python3.12/site-packages/setuptools/build_meta.py"", line 320, in run_setup
          exec(code, locals())
        File ""<string>"", line 32, in <module>
      RuntimeError: Python version 2.7 or 3.4+ is required.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
"
https://github.com/astoycos/Mini_Project2,No requirements found
https://github.com/RGLab/scamp,No requirements found
https://github.com/magicsunday/pico,No requirements found
https://github.com/wanglimin/MRCNN-Scene-Recognition,No requirements found
https://github.com/labixiaoK/lda,No requirements found
https://github.com/ShichengChen/Domain-Adversarial-Training-of-Neural-Networks,No requirements found
https://github.com/pmorerio/dl-uncertainty,No requirements found
https://github.com/zuoqing1988/mobile-sphereface-caffe,No requirements found
https://github.com/kyunghwan/darknet_v3,No requirements found
https://github.com/hollygrimm/cyclegan-keras-art-attrs,No requirements found
https://github.com/lancopku/Chinese-Literature-NER-RE-Dataset,No requirements found
https://github.com/pfnet-research/vat_nmt,No requirements found
https://github.com/D-X-Y/DXY-Projects/tree/master/MSPLD,No requirements found
https://github.com/WolfNiu/polite-dialogue-generation,No requirements found
https://github.com/traveller59/second.pytorch,No requirements found
https://github.com/yumaloop/mobilenetV2-cifar,No requirements found
https://github.com/SeonbeomKim/TensorFlow-lstm-char-cnn,No requirements found
https://github.com/MaStatLab/BGCR,No requirements found
https://github.com/BeyremKh/ASNI,No requirements found
https://github.com/FoelliX/AQL-System,No requirements found
https://github.com/JakobHavtorn/nn,No requirements found
https://github.com/rbrthogan/GAz,No requirements found
https://github.com/liutianlin0121/contSentEmbed,No requirements found
https://github.com/kingcheng2000/GAN,No requirements found
https://github.com/averyfallson/rmffn,No requirements found
https://github.com/WelkinYang/Zoneout-Pytorch,No requirements found
https://github.com/BH94/cGANs-tensorflow-Python,No matching distribution found
https://github.com/landeros10/infoganJL,No requirements found
https://github.com/bioinformatics-ua/patienttm,No requirements found
https://github.com/Montia/bw2color,No requirements found
https://github.com/NeekhilD/Learning-Competition,No requirements found
https://github.com/nightrome/cocostuff10k,No requirements found
https://github.com/JamesGlare/Neural-Net-LabView-DLL,No requirements found
https://github.com/danielamassiceti/geneval_visdial,No requirements found
https://github.com/mingjund/mapudungun-corpus,No requirements found
https://github.com/newalexander/supervised-cadres,"Failed:   error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmp0pgyctdx/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py"", line 353, in <module>
          main()
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmp0pgyctdx/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py"", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmp0pgyctdx/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py"", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-build-env-6l7mfg30/overlay/lib/python3.12/site-packages/setuptools/build_meta.py"", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-build-env-6l7mfg30/overlay/lib/python3.12/site-packages/setuptools/build_meta.py"", line 304, in _get_build_requires
          self.run_setup()
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-build-env-6l7mfg30/overlay/lib/python3.12/site-packages/setuptools/build_meta.py"", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
        File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-build-env-6l7mfg30/overlay/lib/python3.12/site-packages/setuptools/build_meta.py"", line 320, in run_setup
          exec(code, locals())
        File ""<string>"", line 34, in <module>
      RuntimeError: Python version 2.7 or 3.4+ is required.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
"
https://github.com/saransh317/YOLOv3-Easy-Implementation,No requirements found
https://github.com/qubole/qubole-log-datasets,No requirements found
https://github.com/ye-kyaw-thu/myword,No requirements found
https://github.com/jrterven/backsub,No requirements found
https://github.com/ds4dm/sGat,No requirements found
https://github.com/youzhonghui/ANL,No requirements found
https://github.com/Gauravshahare/ADVERSIAL_AUTOENCODER,No requirements found
https://github.com/njross/optimizer,No requirements found
https://github.com/HarukiYqM/Non-Local-Sparse-Attention,No requirements found
https://github.com/misho104/susy_cross_section,No requirements found
https://github.com/cc-rmd-epibio/domain-adaptation-meta-analysis,"Failed: ERROR: Exception:
Traceback (most recent call last):
  File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpq6odwabr/lib/python3.12/site-packages/pip/_internal/cli/base_command.py"", line 105, in _run_wrapper
    status = _inner_run()
             ^^^^^^^^^^^^
  File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpq6odwabr/lib/python3.12/site-packages/pip/_internal/cli/base_command.py"", line 96, in _inner_run
    return self.run(options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpq6odwabr/lib/python3.12/site-packages/pip/_internal/cli/req_command.py"", line 67, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpq6odwabr/lib/python3.12/site-packages/pip/_internal/commands/install.py"", line 379, in run
    requirement_set = resolver.resolve(
                      ^^^^^^^^^^^^^^^^^
  File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpq6odwabr/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/resolver.py"", line 95, in resolve
    result = self._result = resolver.resolve(
                            ^^^^^^^^^^^^^^^^^
  File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpq6odwabr/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py"", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpq6odwabr/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py"", line 397, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpq6odwabr/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py"", line 173, in _add_to_criteria
    if not criterion.candidates:
           ^^^^^^^^^^^^^^^^^^^^
  File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpq6odwabr/lib/python3.12/site-packages/pip/_vendor/resolvelib/structs.py"", line 156, in __bool__
    return bool(self._sequence)
           ^^^^^^^^^^^^^^^^^^^^
  File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpq6odwabr/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py"", line 174, in __bool__
    return any(self)
           ^^^^^^^^^
  File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpq6odwabr/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py"", line 162, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
                       ^^^^^^^^
  File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpq6odwabr/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py"", line 53, in _iter_built
    candidate = func()
                ^^^^^^
  File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpq6odwabr/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/factory.py"", line 187, in _make_candidate_from_link
    base: Optional[BaseCandidate] = self._make_base_candidate_from_link(
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpq6odwabr/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/factory.py"", line 233, in _make_base_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
                                       ^^^^^^^^^^^^^^
  File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpq6odwabr/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py"", line 304, in __init__
    super().__init__(
  File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpq6odwabr/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py"", line 159, in __init__
    self.dist = self._prepare()
                ^^^^^^^^^^^^^^^
  File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpq6odwabr/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py"", line 236, in _prepare
    dist = self._prepare_distribution()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpq6odwabr/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py"", line 315, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpq6odwabr/lib/python3.12/site-packages/pip/_internal/operations/prepare.py"", line 527, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpq6odwabr/lib/python3.12/site-packages/pip/_internal/operations/prepare.py"", line 642, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpq6odwabr/lib/python3.12/site-packages/pip/_internal/operations/prepare.py"", line 72, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpq6odwabr/lib/python3.12/site-packages/pip/_internal/distributions/sdist.py"", line 56, in prepare_distribution_metadata
    self._install_build_reqs(finder)
  File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpq6odwabr/lib/python3.12/site-packages/pip/_internal/distributions/sdist.py"", line 126, in _install_build_reqs
    build_reqs = self._get_build_requires_wheel()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpq6odwabr/lib/python3.12/site-packages/pip/_internal/distributions/sdist.py"", line 103, in _get_build_requires_wheel
    return backend.get_requires_for_build_wheel()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpq6odwabr/lib/python3.12/site-packages/pip/_internal/utils/misc.py"", line 701, in get_requires_for_build_wheel
    return super().get_requires_for_build_wheel(config_settings=cs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpq6odwabr/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_impl.py"", line 166, in get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpq6odwabr/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_impl.py"", line 321, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
  File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmpq6odwabr/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py"", line 77, in _build_backend
    obj = import_module(mod_path)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File ""/opt/homebrew/Cellar/python@3.12/3.12.8/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py"", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ""<frozen importlib._bootstrap>"", line 1387, in _gcd_import
  File ""<frozen importlib._bootstrap>"", line 1360, in _find_and_load
  File ""<frozen importlib._bootstrap>"", line 1310, in _find_and_load_unlocked
  File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
  File ""<frozen importlib._bootstrap>"", line 1387, in _gcd_import
  File ""<frozen importlib._bootstrap>"", line 1360, in _find_and_load
  File ""<frozen importlib._bootstrap>"", line 1331, in _find_and_load_unlocked
  File ""<frozen importlib._bootstrap>"", line 935, in _load_unlocked
  File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
  File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
  File ""/private/var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/pip-build-env-mypbaz0o/overlay/lib/python3.12/site-packages/setuptools/__init__.py"", line 9, in <module>
    import distutils.core
ModuleNotFoundError: No module named 'distutils'

"
https://github.com/sylvchev/dataset-ssvep-exoskeleton,No requirements found
https://github.com/johnsonkee/graduate_design,No requirements found
https://github.com/spcl/ucudnn,No requirements found
https://github.com/lxdragoon/Modified-mnist,No requirements found
https://github.com/HolyBayes/VarDropPytorch,Success
https://github.com/nmeripo/Reducing-the-Dimensionality-of-Data-with-Neural-Networks,No requirements found
https://github.com/hannorein/oec_outreach,No requirements found
https://github.com/Stick-To/RefineDet-tensorflow,No requirements found
https://github.com/MindSpore-paper-code-3/code8/tree/main/FaceQualityAssessment,No requirements found
https://github.com/PaulAlbert31/LabelNoiseCorrection,"Failed: ERROR: Invalid requirement: 'blas=1.0=mkl': Expected end or semicolon (after name and no valid version specifier)
    blas=1.0=mkl
        ^ (from line 1 of /var/folders/94/9pgns_s52bs1szs3my5xd3jc0000gn/T/tmp30cztud1)
Hint: = is not a valid operator. Did you mean == ?
"
https://github.com/andyxingxl/Deformable-generator,No requirements found
https://github.com/vicdolean/schwarz,No requirements found
https://github.com/cybertronai/pytorch-lamb,No requirements found
https://github.com/EmmanuelSchaan/cmb_lensing_noise,No requirements found
https://github.com/Shall-Ven/Activation-Attack,No requirements found
https://github.com/saraswat/munkhdalai-nse,No requirements found
https://github.com/sohaib50k/RESIST-Iris-template-reconstruction,No requirements found
https://github.com/rmalav15/Super-SloMo,No requirements found
https://github.com/tlienart/EPBP,No requirements found
https://github.com/170928/-Review-Proximal-Policy-Optimization-Algorithms,No requirements found
https://github.com/Mind23-2/MindCode-22,No requirements found
https://github.com/trishac97/ML-Policy-PoW,No requirements found
https://github.com/meelgroup/deweight,No requirements found
https://github.com/IntensityTools/MultipoleExpansion,No requirements found
https://github.com/EpistasisLab/regression-benchmark,No requirements found
https://github.com/shizenglin/Deep-NCL,No requirements found
https://github.com/kasaai/ctgan,No requirements found
https://github.com/Jerryten/model_nlp,No requirements found
https://github.com/cmu-safari/segram,No requirements found
https://github.com/rjtshrm/point-normals-upsampling,No matching distribution found
https://github.com/datadog/ssss-paper-code,No requirements found
https://github.com/facebookresearch/measuring-emergent-comm,No requirements found
